#!/usr/bin/env perl
use Time::HiRes qw(usleep nanosleep);
$openRTSP = "./openRTSP";
$openRTSPPara = "-Q -b 300000 -d 1200";
for $num (0..299)
{
  if ($pid = fork)
  {
    usleep(100000);
  }
  elsif (defined $pid)
  {
    $streamNum = (($num % 60) + 1);
    $log_id = sprintf("%04d",$num+1);
    $url = "rtsp://192.168.0.99:8554/live$streamNum";
    #printf("\n$openRTSP $openRTSPPara $url 2>&1 | tee log/session_${log_id}.log\n");
    exec("$openRTSP $openRTSPPara $url 2>&1 | tee log/session_${log_id}.log");
    last;
  }
}
